#!/usr/bin/env bash
max_charge=`system_profiler -detailLevel basic SPPowerDataType | grep mAh | grep Capacity | awk '{print $5 }'`
actual_charge=`system_profiler -detailLevel basic SPPowerDataType | grep mAh | grep Remaining | awk '{print $4 }'`
avail=$(echo "scale=2; $actual_charge / $max_charge * 100" | bc)
avail=`echo $avail | cut -d . -f 1`
echo $avail